# Generated by Django 3.1.1 on 2020-10-12 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='book',
            name='pubdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='PUBDATE'),
            preserve_default=False,
        ),
    ]
