# Generated by Django 3.1.1 on 2020-10-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='TITLE')),
                ('author', models.CharField(max_length=200, verbose_name='AUTHOR')),
                ('publisher', models.CharField(max_length=100, verbose_name='PUBLISHER')),
                ('pub_date', models.DateTimeField(verbose_name='PUB_DATE')),
                ('price', models.IntegerField(default=0, verbose_name='PRICE')),
                ('description', models.CharField(max_length=1000, verbose_name='DESCRIPTION')),
                ('image', models.URLField(verbose_name='IMAGE')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title', 'author', 'isbn'],
            },
        ),
    ]
