# Generated by Django 3.1.1 on 2020-10-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20201012_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['isbn'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
