# Generated by Django 3.1.1 on 2020-10-30 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='TITLE')),
                ('professor', models.CharField(max_length=30, verbose_name='PROFESSOR')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Sugang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, verbose_name='STUDENT_ID')),
                ('name', models.CharField(max_length=30, verbose_name='NAME')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DT')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sugang.course')),
            ],
            options={
                'ordering': ('student_id',),
            },
        ),
    ]
