# Generated by Django 3.1.1 on 2020-09-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=9, verbose_name='STUDENT ID')),
                ('name', models.CharField(max_length=50, verbose_name='NAME')),
                ('major', models.CharField(max_length=50, verbose_name='MAJOR')),
                ('grade', models.CharField(max_length=1, verbose_name='GRADE')),
                ('status', models.CharField(max_length=50, verbose_name='STATUS')),
                ('email', models.EmailField(max_length=50, verbose_name='EMAIL')),
            ],
            options={
                'ordering': ('student_id',),
            },
        ),
    ]
