# Generated by Django 3.1.1 on 2020-11-12 12:02

import baseball.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='NAME')),
                ('hometown', models.CharField(max_length=30, verbose_name='HOMETOWN')),
                ('stadium', models.CharField(max_length=30, verbose_name='STADIUM')),
                ('founding_day', models.DateField(verbose_name='FOUNDING_DAY')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='NAME')),
                ('image', baseball.fields.ThumbnailImageField(upload_to='baseball/%Y/%m', verbose_name='IMAGE')),
                ('position', models.CharField(max_length=30, verbose_name='POSITION')),
                ('birth_day', models.DateField(verbose_name='BIRTH_DAY')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball.team')),
            ],
        ),
    ]
